### PR TITLE
Added Lets Encrypt scripts for SSL certificates

### PR DESCRIPTION
**Pull request by falkogloeckler**
Please test and merge if successful

### CODE REVIEW

**Comment by enmust** [comment]
Hmm... this doesn't work here. Nginx here is just to serve vue app in a dockerized environment. I added our reverse proxy to new repo in github and invited you. 

Also the init-letsencrypt.sh script currently fails because it can't authorize our server (http-01 challenge fails). I also already tested with lets encrypt and I believe I should be able to set it up with ease. I can generate the certs and add them to nginx conf but I just need that the DNS A records answer to our server IP. new.geocase.eu would equal new ui, api.geocase.eu would be api, thumbnail-service could be thumbs, img or images and maybe map service could be map.geocase.eu etc.

**Review by enmust — COMMENTED** [review]
comment added to pull request

**Comment by falkogloeckler** [comment]
OK, thanks! I added the A record for `new.geocase.eu` in our DNS referencing your IP.

Please set in `init-letsencrypt.sh` only the subdomain new.geocase.eu in order to test it.
Use
`domains=(new.geocase.eu)`
instead of
`domains=(geocase.eu new.geocase.eu bms.geocase.eu api.geocase.eu test.geocase.eu www.geocase.eu thumbs.geocase.eu images.geocase.eu img.geocase.eu)` 

If you can use any other way to create SSL certificates it would also be fine.
This branch is only intended to have a nicely integrated and automated renewal of certificates using Let's Encrypt

**Comment by falkogloeckler** [comment]
> I can generate the certs and add them to nginx conf but I just need that the DNS A records answer to our server IP. new.geocase.eu would equal new ui, api.geocase.eu would be api, thumbnail-service could be thumbs, img or images and maybe map service could be map.geocase.eu etc.

I added `api.geocase.eu`, `map.geocase.eu` and `images.geocase.eu` to the DNS as well.

**Comment by enmust** [comment]
Conf updated and apps working under new domains

**Pull request closed without merging**
